schemes:
  gruvbox: &gruvbox
    # Default colors
    primary:
      # hard contrast:
      #background: '#282828'
      background: '#1d2021'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  embark: &embark
    primary:
      background: '0x1e1c31'
      foreground: '0xcbe3e7'
    cursor:
      text: '0x1e1c31'
      cursor: '0xa1efd3'
    normal:
      black: '0x1e1c31'
      red: '0xf48fb1'
      green: '0xa1efd3'
      yellow: '0xffe6b3'
      blue: '0x91ddff'
      magenta: '0xd4bfff'
      cyan: '0x87dfeb'
      white: '0xcbe3e7'
    bright:
      black: '0x585273'
      red: '0xf02e6e'
      green: '0x62d196'
      yellow: '0xf2b482'
      blue: '0x65b2ff'
      magenta: '0xa37acc'
      cyan: '0x63f2f1'
      white: '0x8a889d'

window:
  title: Alacritty
  dynamic_padding: true
  decorations: none
  padding:
    x: 10
    y: 10

scrolling:
  history: 5000

colors: *gruvbox

font:
  normal:
    family: "FuraMono Nerd Font Mono"
    style: Regular

  bold:
    family: "FuraMono Nerd Font Mono"
    style: Bold

  italic:
    family: "FuraMono Nerd Font Mono"
    style: Italic

  size: 16.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: V,        mods: Command, action: Paste                        }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: Q,        mods: Control, chars: "\x11"                        }
  - { key: N,        mods: Command, command: { program: "open", args: ["-nb", "io.alacritty"] } }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
  - { key: F3,                      chars: "\x1bOR"                      }
  - { key: F4,                      chars: "\x1bOS"                      }
  - { key: F5,                      chars: "\x1b[15~"                    }
  - { key: F6,                      chars: "\x1b[17~"                    }
  - { key: F7,                      chars: "\x1b[18~"                    }
  - { key: F8,                      chars: "\x1b[19~"                    }
  - { key: F9,                      chars: "\x1b[20~"                    }
  - { key: F10,                     chars: "\x1b[21~"                    }
  - { key: F11,                     chars: "\x1b[23~"                    }
  - { key: F12,                     chars: "\x1b[24~"                    }
  - { key: F1,       mods: Shift,   chars: "\x1b[1;2P"                   }
  - { key: F2,       mods: Shift,   chars: "\x1b[1;2Q"                   }
  - { key: F3,       mods: Shift,   chars: "\x1b[1;2R"                   }
  - { key: F4,       mods: Shift,   chars: "\x1b[1;2S"                   }
  - { key: F5,       mods: Shift,   chars: "\x1b[15;2~"                  }
  - { key: F6,       mods: Shift,   chars: "\x1b[17;2~"                  }
  - { key: F7,       mods: Shift,   chars: "\x1b[18;2~"                  }
  - { key: F8,       mods: Shift,   chars: "\x1b[19;2~"                  }
  - { key: F9,       mods: Shift,   chars: "\x1b[20;2~"                  }
  - { key: F10,      mods: Shift,   chars: "\x1b[21;2~"                  }
  - { key: F11,      mods: Shift,   chars: "\x1b[23;2~"                  }
  - { key: F12,      mods: Shift,   chars: "\x1b[24;2~"                  }
  - { key: F1,       mods: Control, chars: "\x1b[1;5P"                   }
  - { key: F2,       mods: Control, chars: "\x1b[1;5Q"                   }
  - { key: F3,       mods: Control, chars: "\x1b[1;5R"                   }
  - { key: F4,       mods: Control, chars: "\x1b[1;5S"                   }
  - { key: F5,       mods: Control, chars: "\x1b[15;5~"                  }
  - { key: F6,       mods: Control, chars: "\x1b[17;5~"                  }
  - { key: F7,       mods: Control, chars: "\x1b[18;5~"                  }
  - { key: F8,       mods: Control, chars: "\x1b[19;5~"                  }
  - { key: F9,       mods: Control, chars: "\x1b[20;5~"                  }
  - { key: F10,      mods: Control, chars: "\x1b[21;5~"                  }
  - { key: F11,      mods: Control, chars: "\x1b[23;5~"                  }
  - { key: F12,      mods: Control, chars: "\x1b[24;5~"                  }
  - { key: F1,       mods: Alt,     chars: "\x1b[1;6P"                   }
  - { key: F2,       mods: Alt,     chars: "\x1b[1;6Q"                   }
  - { key: F3,       mods: Alt,     chars: "\x1b[1;6R"                   }
  - { key: F4,       mods: Alt,     chars: "\x1b[1;6S"                   }
  - { key: F5,       mods: Alt,     chars: "\x1b[15;6~"                  }
  - { key: F6,       mods: Alt,     chars: "\x1b[17;6~"                  }
  - { key: F7,       mods: Alt,     chars: "\x1b[18;6~"                  }
  - { key: F8,       mods: Alt,     chars: "\x1b[19;6~"                  }
  - { key: F9,       mods: Alt,     chars: "\x1b[20;6~"                  }
  - { key: F10,      mods: Alt,     chars: "\x1b[21;6~"                  }
  - { key: F11,      mods: Alt,     chars: "\x1b[23;6~"                  }
  - { key: F12,      mods: Alt,     chars: "\x1b[24;6~"                  }
  - { key: F1,       mods: Command, chars: "\x1b[1;3P"                   }
  - { key: F2,       mods: Command, chars: "\x1b[1;3Q"                   }
  - { key: F3,       mods: Command, chars: "\x1b[1;3R"                   }
  - { key: F4,       mods: Command, chars: "\x1b[1;3S"                   }
  - { key: F5,       mods: Command, chars: "\x1b[15;3~"                  }
  - { key: F6,       mods: Command, chars: "\x1b[17;3~"                  }
  - { key: F7,       mods: Command, chars: "\x1b[18;3~"                  }
  - { key: F8,       mods: Command, chars: "\x1b[19;3~"                  }
  - { key: F9,       mods: Command, chars: "\x1b[20;3~"                  }
  - { key: F10,      mods: Command, chars: "\x1b[21;3~"                  }
  - { key: F11,      mods: Command, chars: "\x1b[23;3~"                  }
  - { key: F12,      mods: Command, chars: "\x1b[24;3~"                  }
  - { key: Left,     mods: Command,       chars: "\x06\x48" }
  - { key: Down,     mods: Command,       chars: "\x06\x4a" }
  - { key: Up,       mods: Command,       chars: "\x06\x4b" }
  - { key: Right,    mods: Command,       chars: "\x06\x4c" }
  - { key: Key1,     mods: Command,  command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 1"] } }
  - { key: Key2,     mods: Command,  command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 2"] } }
  - { key: Key3,     mods: Command,  command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 3"] } }
  - { key: Key4,     mods: Command,  command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 4"] } }
  - { key: D,        mods: Command,  command: { program: "/usr/local/bin/tmux", args: ["detach"] } }
  - { key: S,    mods: Command,       chars: "\x01\x73" }
  - { key: W,    mods: Command,       chars: "\x01\x71" }
  - { key: P,    mods: Command,       chars: "\x01\x69" }
  - { key: O,    mods: Command,       chars: "\x01\x75" }
  - { key: C,    mods: Command,       chars: "\x01\x63" }
  - { key: F,    mods: Command,       chars: "\x01\x46" }
  - { key: E,    mods: Command,       chars: "\x01\x76" }
  - { key: Z,    mods: Command,       chars: "\x01\x7a" }
  - { key: I,    mods: Command,       chars: "\x01\x6f" }
