schemes:
  gruvbox: &gruvbox
    # Default colors
    primary:
      # hard contrast:
      #background: '#282828'
      background: '#1d2021'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  embark: &embark
    primary:
      background: '0x1e1c31'
      foreground: '0xcbe3e7'
    cursor:
      text: '0x1e1c31'
      cursor: '0xa1efd3'
    normal:
      black: '0x1e1c31'
      red: '0xf48fb1'
      green: '0xa1efd3'
      yellow: '0xffe6b3'
      blue: '0x91ddff'
      magenta: '0xd4bfff'
      cyan: '0x87dfeb'
      white: '0xcbe3e7'
    bright:
      black: '0x585273'
      red: '0xf02e6e'
      green: '0x62d196'
      yellow: '0xf2b482'
      blue: '0x65b2ff'
      magenta: '0xa37acc'
      cyan: '0x63f2f1'
      white: '0x8a889d'

window:
  title: Alacritty
  dynamic_padding: true
  padding:
    x: 10
    y: 10

scrolling:
  history: 5000

colors: *gruvbox

font:
  normal:
    family: "Hack Nerd Font Mono"
    style: Regular

  bold:
    family: "Hack Nerd Font Mono"
    style: Bold

  italic:
    family: "Hack Nerd Font Mono"
    style: Italic

  size: 16.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

# use "xxd -psd" to figure out the keycodes
key_bindings:
  - { key: C,        mods: Command,        chars: "\x01\x63" }
  - { key: D,        mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["detach"] } }
  - { key: E,        mods: Command,        chars: "\x01\x76" }
  - { key: F,        mods: Command,        chars: "\x01\x46" }
  - { key: H,        mods: Command,        chars: "\x01\x68" }
  - { key: I,        mods: Command,        chars: "\x01\x69" }
  - { key: Key1,     mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 1"] } }
  - { key: Key2,     mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 2"] } }
  - { key: Key3,     mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 3"] } }
  - { key: Key4,     mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 4"] } }
  - { key: Key5,     mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 5"] } }
  - { key: Key6,     mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 6"] } }
  - { key: Key7,     mods: Command,        command: { program: "/usr/local/bin/tmux", args: ["select-window", "-t 7"] } }
  - { key: N,        mods: Command,        command: { program: "open", args: ["-nb", "io.alacritty"] } }
  - { key: O,        mods: Command,        chars: "\x01\x6f" }
  - { key: P,        mods: Command,        chars: "\x01\x70" }
  - { key: Q,        mods: Command,        action: Quit }
  - { key: Q,        mods: Control,        chars: "\x11" }
  - { key: S,        mods: Command,        chars: "\x01\x73" }
  - { key: V,        mods: Command,        action: Paste }
  - { key: W,        mods: Command,        chars: "\x01\x71" }
  - { key: Z,        mods: Command,        chars: "\x01\x7a" }
