schemes:
  tokyontight_dark: &tokyontight_dark
    primary:
      background: '0x1a1b26'
      foreground: '0xc0caf5'

    normal:
      black:   '0x15161e'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xbb9af7'
      cyan:    '0x7dcfff'
      white:   '0xa9b1d6'

    bright:
      black:   '0x414868'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xbb9af7'
      cyan:    '0x7dcfff'
      white:   '0xc0caf5'

    indexed_colors:
      - { index: 16, color: '0xff9e64' }
      - { index: 17, color: '0xdb4b4b' }

  tokyontight_light: &tokyontight_light
    primary:
      background: '0xe1e2e7'
      foreground: '0x3760bf'

    normal:
      black:   '0xe9e9ed'
      red:     '0xf52a65'
      green:   '0x587539'
      yellow:  '0x8c6c3e'
      blue:    '0x2e7de9'
      magenta: '0x9854f1'
      cyan:    '0x007197'
      white:   '0x6172b0'

    bright:
      black:   '0xa1a6c5'
      red:     '0xf52a65'
      green:   '0x587539'
      yellow:  '0x8c6c3e'
      blue:    '0x2e7de9'
      magenta: '0x9854f1'
      cyan:    '0x007197'
      white:   '0x3760bf'

    indexed_colors:
      - { index: 16, color: '0xb15c00' }
      - { index: 17, color: '0xc64343' }

  catppuccin_latte: &catppuccin_latte
    primary:
      background: "#EFF1F5"
      foreground: "#4C4F69"
      dim_foreground: "#4C4F69"
      bright_foreground: "#4C4F69"

    cursor:
      text: "#EFF1F5"
      cursor: "#DC8A78"
    vi_mode_cursor:
      text: "#EFF1F5"
      cursor: "#7287FD"

    search:
      matches:
        foreground: "#EFF1F5"
        background: "#6C6F85"
      focused_match:
        foreground: "#EFF1F5"
        background: "#40A02B"
      footer_bar:
        foreground: "#EFF1F5"
        background: "#6C6F85"

    hints:
      start:
        foreground: "#EFF1F5"
        background: "#DF8E1D"
      end:
        foreground: "#EFF1F5"
        background: "#6C6F85"

    selection:
      text: "#EFF1F5"
      background: "#DC8A78"

    normal:
      black: "#5C5F77"
      red: "#D20F39"
      green: "#40A02B"
      yellow: "#DF8E1D"
      blue: "#1E66F5"
      magenta: "#EA76CB"
      cyan: "#179299"
      white: "#ACB0BE"

    bright:
      black: "#6C6F85"
      red: "#D20F39"
      green: "#40A02B"
      yellow: "#DF8E1D"
      blue: "#1E66F5"
      magenta: "#EA76CB"
      cyan: "#179299"
      white: "#BCC0CC"

    dim:
      black: "#5C5F77"
      red: "#D20F39"
      green: "#40A02B"
      yellow: "#DF8E1D"
      blue: "#1E66F5"
      magenta: "#EA76CB"
      cyan: "#179299"
      white: "#ACB0BE"

    indexed_colors:
      - { index: 16, color: "#FE640B" }
      - { index: 17, color: "#DC8A78" }

  catppuccin_mocha: &catppuccin_mocha
    primary:
      background: "#1E1E2E"
      foreground: "#CDD6F4"
      dim_foreground: "#CDD6F4"
      bright_foreground: "#CDD6F4"

    cursor:
      text: "#1E1E2E"
      cursor: "#F5E0DC"
    vi_mode_cursor:
      text: "#1E1E2E"
      cursor: "#B4BEFE"

    search:
      matches:
        foreground: "#1E1E2E"
        background: "#A6ADC8"
      focused_match:
        foreground: "#1E1E2E"
        background: "#A6E3A1"
      footer_bar:
        foreground: "#1E1E2E"
        background: "#A6ADC8"

    hints:
      start:
        foreground: "#1E1E2E"
        background: "#F9E2AF"
      end:
        foreground: "#1E1E2E"
        background: "#A6ADC8"

    selection:
      text: "#1E1E2E"
      background: "#F5E0DC"

    normal:
      black: "#45475A"
      red: "#F38BA8"
      green: "#A6E3A1"
      yellow: "#F9E2AF"
      blue: "#89B4FA"
      magenta: "#F5C2E7"
      cyan: "#94E2D5"
      white: "#BAC2DE"

    bright:
      black: "#585B70"
      red: "#F38BA8"
      green: "#A6E3A1"
      yellow: "#F9E2AF"
      blue: "#89B4FA"
      magenta: "#F5C2E7"
      cyan: "#94E2D5"
      white: "#A6ADC8"

    dim:
      black: "#45475A"
      red: "#F38BA8"
      green: "#A6E3A1"
      yellow: "#F9E2AF"
      blue: "#89B4FA"
      magenta: "#F5C2E7"
      cyan: "#94E2D5"
      white: "#BAC2DE"

    indexed_colors:
      - { index: 16, color: "#FAB387" }
      - { index: 17, color: "#F5E0DC" }

  dracula: &dracula
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '0x44475a'
        background: '0x50fa7b'
      focused_match:
        foreground: '0x44475a'
        background: '0xffb86c'
      bar:
        background: '0x282a36'
        foreground: '0xf8f8f2'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '0x44475a'
    normal:
      black:   '0x000000'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xbd93f9'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xbfbfbf'
    bright:
      black:   '0x4d4d4d'
      red:     '0xff6e67'
      green:   '0x5af78e'
      yellow:  '0xf4f99d'
      blue:    '0xcaa9fa'
      magenta: '0xff92d0'
      cyan:    '0x9aedfe'
      white:   '0xe6e6e6'
    dim:
      black:   '0x14151b'
      red:     '0xff2222'
      green:   '0x1ef956'
      yellow:  '0xebf85b'
      blue:    '0x4d5b86'
      magenta: '0xff46b0'
      cyan:    '0x59dffc'
      white:   '0xe6e6d1'

  gruvbox: &gruvbox
    primary:
      background: '#1d2021'
      foreground: '#ebdbb2'

    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  embark: &embark
    primary:
      background: '0x1e1c31'
      foreground: '0xcbe3e7'
    cursor:
      text: '0x1e1c31'
      cursor: '0xa1efd3'
    normal:
      black: '0x1e1c31'
      red: '0xf48fb1'
      green: '0xa1efd3'
      yellow: '0xffe6b3'
      blue: '0x91ddff'
      magenta: '0xd4bfff'
      cyan: '0x87dfeb'
      white: '0xcbe3e7'
    bright:
      black: '0x585273'
      red: '0xf02e6e'
      green: '0x62d196'
      yellow: '0xf2b482'
      blue: '0x65b2ff'
      magenta: '0xa37acc'
      cyan: '0x63f2f1'
      white: '0x8a889d'

window:
  decorations: "buttonless"
  title: Terminal
  dynamic_padding: true
  padding:
    x: 10
    y: 10

scrolling:
  history: 5000
  multiplier: 3

colors: *tokyontight_dark

font:
  normal:
    family: "JetBrainsMonoNL Nerd Font Mono"
    style: Regular

  bold:
    family: "JetBrainsMonoNL Nerd Font Mono"
    # style: Regular
    style: Bold

  italic:
    family: "JetBrainsMonoNL Nerd Font Mono"
    style: Italic

  size: 16.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

# use "xxd -psd" to figure out the keycodes
key_bindings:
  - { key: C,        mods: Command,        chars: "\x01\x63" } # sends Ctrl + a
  - { key: S,        mods: Command,        chars: "\x01\x73" } # sends Ctrl + s
  - { key: D,        mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["detach"] } }
  - { key: E,        mods: Command,        chars: "\x01\x76" }
  - { key: F,        mods: Command,        chars: "\x01\x46" }
  - { key: H,        mods: Command,        chars: "\x01\x68" }
  - { key: I,        mods: Command,        chars: "\x01\x69" }
  - { key: Key1,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 1"] } }
  - { key: Key2,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 2"] } }
  - { key: Key3,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 3"] } }
  - { key: Key4,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 4"] } }
  - { key: Key5,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 5"] } }
  - { key: Key6,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 6"] } }
  - { key: Key7,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 7"] } }
  - { key: L,        mods: Command,        chars: "\x01\x6c" }
  - { key: N,        mods: Command,        action: SpawnNewInstance }
  - { key: O,        mods: Command,        chars: "\x01\x6f" }
  - { key: P,        mods: Command,        chars: "\x01\x70" }
  - { key: Q,        mods: Command,        action: Quit }
  - { key: Q,        mods: Control,        chars: "\x11" }
  - { key: R,        mods: Command,        chars: "\x01\x72" }
  - { key: V,        mods: Command,        action: Paste }
  - { key: W,        mods: Command,        chars: "\x01\x71" }
  - { key: Z,        mods: Command,        chars: "\x01\x7a" }
