schemes:
  catppuccin_latte: &catppuccin_latte
    # Default colors
    primary:
        background: "#EFF1F5" # base
        foreground: "#4C4F69" # text
        # Bright and dim foreground colors
        dim_foreground: "#4C4F69" # text
        bright_foreground: "#4C4F69" # text

    # Cursor colors
    cursor:
        text: "#EFF1F5" # base
        cursor: "#DC8A78" # rosewater
    vi_mode_cursor:
        text: "#EFF1F5" # base
        cursor: "#7287FD" # lavender

    # Search colors
    search:
        matches:
            foreground: "#EFF1F5" # base
            background: "#6C6F85" # subtext0
        focused_match:
            foreground: "#EFF1F5" # base
            background: "#40A02B" # green
        footer_bar:
            foreground: "#EFF1F5" # base
            background: "#6C6F85" # subtext0

    # Keyboard regex hints
    hints:
        start:
            foreground: "#EFF1F5" # base
            background: "#DF8E1D" # yellow
        end:
            foreground: "#EFF1F5" # base
            background: "#6C6F85" # subtext0

    # Selection colors
    selection:
        text: "#EFF1F5" # base
        background: "#DC8A78" # rosewater

    # Normal colors
    normal:
        black: "#5C5F77" # subtext1
        red: "#D20F39" # red
        green: "#40A02B" # green
        yellow: "#DF8E1D" # yellow
        blue: "#1E66F5" # blue
        magenta: "#EA76CB" # pink
        cyan: "#179299" # teal
        white: "#ACB0BE" # surface2

    # Bright colors
    bright:
        black: "#6C6F85" # subtext0
        red: "#D20F39" # red
        green: "#40A02B" # green
        yellow: "#DF8E1D" # yellow
        blue: "#1E66F5" # blue
        magenta: "#EA76CB" # pink
        cyan: "#179299" # teal
        white: "#BCC0CC" # surface1

    # Dim colors
    dim:
        black: "#5C5F77" # subtext1
        red: "#D20F39" # red
        green: "#40A02B" # green
        yellow: "#DF8E1D" # yellow
        blue: "#1E66F5" # blue
        magenta: "#EA76CB" # pink
        cyan: "#179299" # teal
        white: "#ACB0BE" # surface2

    indexed_colors:
        - { index: 16, color: "#FE640B" }
        - { index: 17, color: "#DC8A78" }

  catppuccin_mocha: &catppuccin_mocha
    # Default colors
    primary:
      background: '0x1E1D2F'
      foreground: '0xD9E0EE'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1E1D2F'
      cursor: '0xF5E0DC'

    # Normal colors
    normal:
      black:   '0x6E6C7E'
      red:     '0xF28FAD'
      green:   '0xABE9B3'
      yellow:  '0xFAE3B0'
      blue:    '0x96CDFB'
      magenta: '0xF5C2E7'
      cyan:    '0x89DCEB'
      white:   '0xD9E0EE'

    # Bright colors
    bright:
      black:   '0x988BA2'
      red:     '0xF28FAD'
      green:   '0xABE9B3'
      yellow:  '0xFAE3B0'
      blue:    '0x96CDFB'
      magenta: '0xF5C2E7'
      cyan:    '0x89DCEB'
      white:   '0xD9E0EE'

    indexed_colors:
      - { index: 16, color: '0xF8BD96' }
      - { index: 17, color: '0xF5E0DC' }

  dracula: &dracula
    primary:
      background: '0x282a36'
      foreground: '0xf8f8f2'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '0x44475a'
        background: '0x50fa7b'
      focused_match:
        foreground: '0x44475a'
        background: '0xffb86c'
      bar:
        background: '0x282a36'
        foreground: '0xf8f8f2'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '0x44475a'
    normal:
      black:   '0x000000'
      red:     '0xff5555'
      green:   '0x50fa7b'
      yellow:  '0xf1fa8c'
      blue:    '0xbd93f9'
      magenta: '0xff79c6'
      cyan:    '0x8be9fd'
      white:   '0xbfbfbf'
    bright:
      black:   '0x4d4d4d'
      red:     '0xff6e67'
      green:   '0x5af78e'
      yellow:  '0xf4f99d'
      blue:    '0xcaa9fa'
      magenta: '0xff92d0'
      cyan:    '0x9aedfe'
      white:   '0xe6e6e6'
    dim:
      black:   '0x14151b'
      red:     '0xff2222'
      green:   '0x1ef956'
      yellow:  '0xebf85b'
      blue:    '0x4d5b86'
      magenta: '0xff46b0'
      cyan:    '0x59dffc'
      white:   '0xe6e6d1'

  gruvbox: &gruvbox
    # Default colors
    primary:
      # hard contrast:
      #background: '#282828'
      background: '#1d2021'
      # soft contrast: background = '#32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  embark: &embark
    primary:
      background: '0x1e1c31'
      foreground: '0xcbe3e7'
    cursor:
      text: '0x1e1c31'
      cursor: '0xa1efd3'
    normal:
      black: '0x1e1c31'
      red: '0xf48fb1'
      green: '0xa1efd3'
      yellow: '0xffe6b3'
      blue: '0x91ddff'
      magenta: '0xd4bfff'
      cyan: '0x87dfeb'
      white: '0xcbe3e7'
    bright:
      black: '0x585273'
      red: '0xf02e6e'
      green: '0x62d196'
      yellow: '0xf2b482'
      blue: '0x65b2ff'
      magenta: '0xa37acc'
      cyan: '0x63f2f1'
      white: '0x8a889d'

window:
  decorations: "buttonless"
  title: Terminal
  dynamic_padding: true
  padding:
    x: 10
    y: 10

scrolling:
  history: 5000
  multiplier: 3

colors: *catppuccin_mocha

font:
  normal:
    family: "FiraCode Nerd Font Mono"
    style: Regular

  bold:
    family: "FiraCode Nerd Font Mono"
    # style: Regular
    style: Bold

  italic:
    family: "FiraCode Nerd Font Mono"
    style: Italic

  size: 16.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 1

draw_bold_text_with_bright_colors: true

# use "xxd -psd" to figure out the keycodes
key_bindings:
  - { key: C,        mods: Command,        chars: "\x01\x63" } # sends Ctrl + a
  - { key: S,        mods: Command,        chars: "\x01\x73" } # sends Ctrl + s
  - { key: D,        mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["detach"] } }
  - { key: E,        mods: Command,        chars: "\x01\x76" }
  - { key: F,        mods: Command,        chars: "\x01\x46" }
  - { key: H,        mods: Command,        chars: "\x01\x68" }
  - { key: I,        mods: Command,        chars: "\x01\x69" }
  - { key: Key1,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 1"] } }
  - { key: Key2,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 2"] } }
  - { key: Key3,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 3"] } }
  - { key: Key4,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 4"] } }
  - { key: Key5,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 5"] } }
  - { key: Key6,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 6"] } }
  - { key: Key7,     mods: Command,        command: { program: "/opt/homebrew/bin/tmux", args: ["select-window", "-t 7"] } }
  - { key: L,        mods: Command,        chars: "\x01\x6c" }
  - { key: N,        mods: Command,        action: SpawnNewInstance }
  - { key: O,        mods: Command,        chars: "\x01\x6f" }
  - { key: P,        mods: Command,        chars: "\x01\x70" }
  - { key: Q,        mods: Command,        action: Quit }
  - { key: Q,        mods: Control,        chars: "\x11" }
  - { key: R,        mods: Command,        chars: "\x01\x72" }
  - { key: V,        mods: Command,        action: Paste }
  - { key: W,        mods: Command,        chars: "\x01\x71" }
  - { key: Z,        mods: Command,        chars: "\x01\x7a" }
