- name: link dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/shell/files/{{ item.src }}"
    dest: "{{ home_dir }}/{{ item.dest }}"
    state: link
  with_items:
    - dest: .tigrc
      src: tigrc
    - dest: .gitattributes
      src: gitattributes
    - dest: .gitcommit
      src: gitcommit
    - dest: .gitconfig
      src: gitconfig
    - dest: .gitignore
      src: gitignore

- name: link alacritty configuration
  file:
    src: '{{ ansible_env.PWD }}/roles/shell/files/alacritty'
    dest: '{{ home_dir }}/.config/alacritty'
    state: link

- include: zsh.yml
  when: os_family == 'darwin'
  vars:
    - executable: /usr/local/binzsh/

- include: zsh.yml
  when: os_family == 'debian'
  vars:
    - executable: /usr/binzsh/
