- name: link dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/shell/files/{{ item.src }}"
    dest: "{{ home_dir }}/{{ item.dest }}"
    state: link
  with_items:
    - dest: .gitattributes
      src: gitattributes
    - dest: .gitcommit
      src: gitcommit
    - dest: .gitconfig
      src: gitconfig
    - dest: .gitignore
      src: gitignore
    - dest: .zshrc.local
      src: zshrc.local

- git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ ansible_env.PWD }}/roles/shell/files/zsh/themes/spaceship-prompt"

- git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ ansible_env.PWD }}/roles/shell/files/zsh/plugins/zsh-completions"

- git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.PWD }}/roles/shell/files/zsh/plugins/zsh-autosuggestions"

- name: make zsh the default shell
  shell: 'chsh -s /bin/zsh'

- name: copy .zshrc
  include_role:
    name: common
    tasks_from: copy_file
  vars:
    src: "{{ ansible_env.PWD }}/roles/shell/files/zshrc"
    dest: "{{ home_dir }}/.zshrc"

