- name: link dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/shell/files/{{ item.src }}"
    dest: "{{ home_dir }}/{{ item.dest }}"
    state: link
  with_items:
    - dest: .tigrc
      src: tigrc
    - dest: .gitattributes
      src: gitattributes
    - dest: .gitcommit
      src: gitcommit
    - dest: .gitconfig
      src: gitconfig
    - dest: .gitignore
      src: gitignore

- name: link omf
  file:
    src: '{{ ansible_env.PWD }}/roles/shell/files/fish'
    dest: '{{ home_dir }}/.config/fish'
    state: link

- name: link fish configuration
  file:
    src: '{{ ansible_env.PWD }}/roles/shell/files/omf'
    dest: '{{ home_dir }}/.config/omf'
    state: link

- include: fish.yml
  when: os_family == 'macosx'
  vars:
    - executable: /usr/local/bin/fish

- include: fish.yml
  when: os_family == 'debian'
  vars:
    - executable: /usr/bin/fish
