- hosts: localhost
  connection: local
  roles:
    - { role: 'common' }
    - { role: 'shell' }
    - { role: 'asdf' }
    - { role: 'vim' }
    - { role: 'terminal', when: "os_family == 'macosx'" }
    - { role: 'keyboard', when: "os_family == 'macosx'" }
    - { role: 'osx_defaults', when: "os_family == 'macosx'", tags: 'osx' }
  vars:
    home_dir: '{{ ansible_env.HOME }}'
    dotfiles_dir: '{{ home_dir }}/Developer/dotfiles'
    os_family: "{{ ansible_facts['os_family']|lower }}"

  tasks:
    - debug:
        msg: All done! Go go go little turtle.
