- hosts: localhost
  connection: local
  roles:
    - { role: 'common', tags: [common] }
    - { role: 'shell', tags: [shell] }
    - { role: 'asdf', tags: [shell] }
    - { role: 'vim', tags: [shell] }
    - { role: 'terminal', when: "os_family == 'darwin'" }
    - { role: 'keyboard', when: "os_family == 'darwin'" }
    - { role: 'osx_defaults', when: "os_family == 'darwin'", tags: 'osx' }
  vars:
    home_dir: '{{ ansible_env.HOME }}'
    dotfiles_dir: '{{ home_dir }}/Developer/dotfiles'
    os_family: "{{ ansible_facts['os_family']|lower }}"

  tasks:
    - debug:
        msg: All done! Go go go little turtle.
