- hosts: localhost
  connection: local
  roles:
    - { role: 'common' }
    - { role: 'shell' }
    - { role: 'terminal' }
    - { role: 'asdf' }
    - { role: 'vim' }
    - { role: 'keyboard' }
    - { role: 'macos' }
  vars:
    home_dir: '{{ ansible_env.HOME }}'
    dotfiles_dir: '{{ home_dir }}/Developer/dotfiles'

  tasks:
    - debug:
        msg: All done! Go go go little turtle.
