# Astrolight theme for tmux
set -g status-style "bg=#E1E2E4,fg=#737474"
set -g window-status-current-style "bg=#F7F8F8,fg=#424446"
set -g window-status-style "bg=#E1E2E4,fg=#AEB3B6"
set -g pane-border-style "fg=#B5B9BD"
set -g pane-active-border-style "fg=#3F8CEA"
set -g message-style "bg=#EAEBEB,fg=#424446"
set -g mode-style "bg=#E7E9EB,fg=#424446"

set -g status-left "#[bg=#F7F8F8,fg=#424446] #S #[default] "
set -g status-right "#[bg=#F7F8F8,fg=#737474] %H:%M "
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-separator ""
set -g popup-style "bg=#F7F8F8"
set -g popup-border-style "bg=#F7F8F8,fg=#B5B9BD"
