# Astrodark theme for tmux
set -g status-style "bg=#111317,fg=#9B9FA9"
set -g window-status-current-style "bg=#1A1D23,fg=#ADB0BB"
set -g window-status-style "bg=#111317,fg=#494D56"
set -g pane-border-style "fg=#3A3E47"
set -g pane-active-border-style "fg=#5EB7FF"
set -g message-style "bg=#1E222A,fg=#ADB0BB"
set -g mode-style "bg=#26343F,fg=#ADB0BB"

set -g status-left "#[bg=#1A1D23,fg=#ADB0BB] #S #[default] "
set -g status-right "#[bg=#1A1D23,fg=#9B9FA9] %H:%M "
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-separator ""
set -g popup-style "bg=#1A1D23"
set -g popup-border-style "bg=#1A1D23,fg=#3A3E47"
