return {}
-- return {
--   {
--     "stevearc/conform.nvim",
--     opts = {
--       formatters = {
--         prettier = {
--           -- cwd means "config working directory"
--           require_cwd = true,
--
--           cwd = require("conform.util").root_file {
--             ".prettierrc",
--             ".prettierrc.json",
--             ".prettierrc.yml",
--             ".prettierrc.yaml",
--             ".prettierrc.json5",
--             ".prettierrc.js",
--             ".prettierrc.cjs",
--             ".prettierrc.mjs",
--             ".prettierrc.toml",
--             "prettier.config.js",
--             "prettier.config.cjs",
--             "prettier.config.mjs",
--           },
--         },
--         djlint = {
--           command = "djlint",
--           args = {
--             "--reformat",
--             "--format-js",
--             "--format-css",
--             "-",
--           },
--           to_stdin = true,
--         },
--       },
--       format_on_save = {
--         timeout_ms = 1000,
--       },
--       formatters_by_ft = {
--         jinja = { "djlint" },
--       },
--     },
--   },
--   {
--     "jay-babu/mason-null-ls.nvim",
--     opts = function(_, opts)
--       -- add more things to the ensure_installed table protecting against community packs modifying it
--       opts.ensure_installed = require("astrocore").list_insert_unique(opts.ensure_installed, {
--         "djlint",
--       })
--     end,
--   },
-- }
