- name: link .files
  file:
    src: '{{ ansible_env.PWD }}/roles/asdf/files/{{ item.src }}'
    dest: '{{ home_dir }}/{{ item.dest }}'
    state: link
  with_items:
    - dest: .default-gems
      src: default-gems
    - dest: .default-npm-packages
      src: default-npm-packages
    - dest: .tool-versions
      src: tool-versions
    - dest: .default-python-packages
      src: default-python-packages

- name: add asdf plugins
  shell: |
    asdf plugin-add nodejs || true
    asdf plugin-add rust || true
    asdf plugin-add java || true
    asdf plugin-add deno || true
    asdf plugin-add ruby || true
    asdf plugin-add elixir || true
    asdf plugin-add python || true
    asdf plugin-add erlang || true
  ignore_errors: yes
