- name: link .files
  file:
    src: '{{ ansible_env.PWD }}/roles/asdf/files/{{ item.src }}'
    dest: '{{ home_dir }}/{{ item.dest }}'
    state: link
  with_items:
    - dest: .default-gems
      src: default-gems
    - dest: .default-npm-packages
      src: default-npm-packages
    - dest: .tool-versions
      src: tool-versions
    - dest: .default-python-packages
      src: default-python-packages

- name: check if asdf exists
  stat:
    path: "{{ home_dir }}/.asdf"
  register: asdf_found

- name: install asdf
  shell: |
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.1
    echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.zshrc
    echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.zshrc
  when: asdf_found.stat.exists == False

- name: add asdf plugins
  shell: |
    asdf plugin-add nodejs || true
    asdf plugin-add ruby || true
    asdf plugin-add elixir || true
    asdf plugin-add python || true
    asdf plugin-add erlang || true
  ignore_errors: yes
