  - name: install homebrew
    shell: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  - homebrew_tap:
      name: universal-ctags/universal-ctags
      state: present

  - name: install homebrew package
    homebrew:
      name: "{{ homebrew_packages }}"
      state: present
      update_homebrew: yes
