# https://github.com/geerlingguy/dotfiles/blob/master/.osx

# Display full POSIX path as Finder window title
- osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
    state: present

# Disable the warning when changing a file extension
- osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
    state: present

# Automatically quit printer app once the print jobs complete
- osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
    state: present

# Set a blazingly fast keyboard repeat rate, and make it happen more quickly
- osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 20
    state: present

- osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 1
    state: present

# Require password immediately after sleep or screen saver begins
- osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present

- osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
    state: present

# Disable shadow in screenshots
- osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
    state: present

# Automatically open a new Finder window when a volume is mounted
- osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-ro-root
    type: bool
    value: true
    state: present

- osx_defaults:
    domain: com.apple.frameworks.diskimages
    key: auto-open-rw-root
    type: bool
    value: true
    state: present

- osx_defaults:
    domain: com.apple.finder
    key: OpenWindowForNewRemovableDisk
    type: bool
    value: true
    state: present
