- name: install homebrew cask packages
  ignore_errors: yes
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
  vars:
    homebrew_cask_packages:
      - hammerspoon

- name: link hammerspoon
  file:
    src: "{{ ansible_env.PWD }}/roles/keyboard/files/hammerspoon"
    dest: "{{ home_dir }}/.hammerspoon"
    state: link
