- name: check if homebrew is installed
  shell: command -v brew > /dev/null 2>&1
  register: brew_found
  ignore_errors: yes

- name: install homebrew
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_found.rc == 1

- name: fonts package
  community.general.homebrew_tap:
    name: homebrew/cask-fonts

- name: install homebrew package
  homebrew:
    name: "{{ terminal_packages }}"
    state: present
    update_homebrew: yes

- name: install homebrew package
  homebrew:
    name: "{{ terminal_osx_packages }}"
    state: present
    update_homebrew: yes

- name: install homebrew cask packages
  ignore_errors: yes
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
  vars:
    homebrew_cask_packages:
      - alacritty
      - docker
      - font-hack-nerd-font
      - hyperswitch
      - lulu
      - nextcloud
      - reaper
      - pgadmin4
      - quicklook-json
      - slack
      - the-unarchiver
      - vagrant
      - virtualbox
      - vlc
      - surge-synthesizer
      - keepassxc
