- name: check if homebrew is installed
  shell: command -v brew > /dev/null 2>&1
  register: brew_found
  ignore_errors: yes

- name: install homebrew
  shell: |
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_found == False

- name: install homebrew package
  homebrew:
    name: "{{ terminal_packages }}"
    state: present
    update_homebrew: yes

- name: install homebrew package
  homebrew:
    name: "{{ terminal_osx_packages }}"
    state: present
    update_homebrew: yes

- name: install homebrew cask packages
  ignore_errors: yes
  homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
  vars:
    homebrew_cask_packages:
      - docker
      - font-fira-code
      - homebrew/cask-fonts/font-fira-code
      - homebrew/cask-fonts/font-ibm-plex
      - hyperswitch
      - lulu
      - pgadmin4
      - quicklook-json
      - shiftit
      - slack
      - the-unarchiver
      - vagrant
      - virtualbox
      - vlc
