- hosts: localhost
  connection: local
  roles:
    - { role: 'shell' }
    - { role: 'terminal' }
    - { role: 'asdf' }
    - { role: 'vim' }
    - { role: 'keyboard' }
    - { role: 'macos' }
  vars:
    home_dir: '{{ ansible_env.HOME }}'
    dotfiles_dir: '{{ home_dir }}/Developer/dotfiles'
