-
  hosts: local
  vars:
    home_dir: '{{ ansible_env.HOME }}'
    dotfiles_dir: '{{ home_dir }}/Developer/dotfiles'
  tasks:
    -
      name: 'create .config directory'
      file: 'path="{{ home_dir}}/.config" state=directory'
    -
      name: 'link dotfiles'
      file:
        src: '{{ dotfiles_dir}}/{{ item.src }}'
        dest: '{{ home_dir }}/{{ item.dest }}'
        state: link
      with_items:
        -
          dest: .gitattributes
          src: gitattributes
        -
          dest: .gitcommit
          src: gitcommit
        -
          dest: .gitconfig
          src: gitconfig
        -
          dest: .gitignore
          src: gitignore
        -
          dest: .rspec
          src: rspec
        -
          dest: .zshrc.local
          src: zshrc.local
        -
          dest: .config/nvim
          src: config/nvim
    -
      name: 'setup zsh if file doesn''t exist'
      include_tasks: tasks/copy_file.yml
      vars:
        src: '{{ dotfiles_dir }}/zshrc'
        dest: '{{ home_dir }}/.zshrc'
    -
      name: 'make zsh the default shell'
      shell: 'chsh -s /bin/zsh'
    -
      name: 'setup netrc if file doesn''t exist'
      include_tasks: tasks/copy_file.yml
      vars:
        src: '{{ dotfiles_dir }}/netrc'
        dest: '{{ home_dir }}/.netrc'
    -
      name: 'install homebrew'
      include_tasks: tasks/brew.yml
    -
      name: 'update vim-plug every monday'
      cron:
        name: 'update vim-plug'
        minute: '*/2'
        hour: '7,8,9,10,11,12'
        weekday: 1
        job: '/bin/zsh ~/Developer/dotfiles/cron/update_vim_plug'
    -
      debug: 'msg="All done! Don''t forget to update .zshrc and .netrc"'
